### PR TITLE
Create user configurable variables for various YSF data

### PR DESCRIPTION
**Pull request by nostar**

### CODE REVIEW

**Comment by AndyTaylorTweet** [comment]
@juribeparada / @nostar - please keep this PR in place for now, Andy (@juribeparada) has merged my patch set in (based on your original patch @nostar), I will submit a PR soon to bring this tree closer in-line with your revised work soon (adding all the config entries etc).

**Comment by juribeparada** [comment]
No problem @AndyTaylorTweet

**Comment by nostar** [comment]
Good news!

**Comment by MW0MWZ** [comment]
@nostar I have a PR coming to add the additional work you did for the YSF2xxx and xxx2YSF modes (thank you).

In addition there is a few additional tweaks to make most of the variables default values so that they don't have to appear in the config file to work.

I can see that you have more additions coming along with the P252DMR mode, so if I get that PR submitted (there are still some improvements to come on that) then we can also pull in your new DT1 values and P252DMR code too and then get all of us back in sync....

**Comment by AndyTaylorTweet** [comment]
@nostar I have a PR coming to add the additional work you did for the YSF2xxx and xxx2YSF modes (thank you).

In addition there is a few additional tweaks to make most of the variables default values so that they don't have to appear in the config file to work.

I can see that you have more additions coming along with the P252DMR mode, so if I get that PR submitted (there are still some improvements to come on that) then we can also pull in your new DT1 values and P252DMR code too and then get all of us back in sync....

**Comment by nostar** [comment]
@AndyTaylorTweet This all looks great.  Just notice that I coincidentally at the same time you were doing this, pushed my INI file values that no longer use CM=1 and a radio ID, and most importantly the DT1 values, which are key for this to work.  You should update your patch with the INI file I just pushed, and also use those values for your defaults:
DT1=1,34,97,95,43,3,17,0,0,0

**Comment by AndyTaylorTweet** [comment]
@nostar - yes I saw that, now added the new DT1 value, I'll take another look at your repo regarding your latest changes also.

**Comment by AndyTaylorTweet** [comment]
@nostar - this repo has now pretty much caught up with you - please have a look at over the conflicts, it should be pretty trivial from here go get in line so that future commits will be trivial again :)

**Comment by nostar** [comment]
This specific pull request was for the YSF stuff, which is done so I will close it.

**Comment by nostar** [comment]
@juribeparada / @AndyTaylorTweet I'm not sure if I'm using the pull requests correctly.  I closed this one and added a new one for some simple filename changes I made, but I wonder if there should just be one open general pull request for everything to come, or maybe no pull request at all and just reach out on the pistar forum or email as changes come.

**Comment by juribeparada** [comment]
I can't merge your new PR because it has conflicts. Please check your PR and solve all the conflicts first.

**Comment by AndyTaylorTweet** [comment]
@nostar I think the thing to do here is create a PR for the most recent change you made, then drop your fork and re-fork the repo. From there you should be able to make changes and commit them without any weird side effects.
I'll take care of the most recent changes - once you see those committed here - drop your fork and re-fork it.

We should all be back in sync at that point.

**Comment by nostar** [comment]
@AndyTaylorTweet OK thanks, yeah I just took a crash course on github forks and syncing, I never set my fork up right from the start anyway, so after you do your thing I'll do it right this time.

**Comment by AndyTaylorTweet** [comment]
we're all always learning :)

**Pull request closed without merging**
